### ISSUE TITLE
Getting an exception executing specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#125]
**Steps to replicate**
Getting an exception on executing specs from [project](https://github.com/getgauge/gauge-test-apps/tree/master/basic-java)
```
panic: runtime error: index out of range

goroutine 72 [running]:
panic(0x320b80, 0x4205c00e0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/getgauge/html-report/generator.toFileName(0x0, 0x0, 0x12, 0x0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:278 +0x7b
github.com/getgauge/html-report/generator.toFragments(0x420768a40, 0x2, 0x2, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:296 +0x70f
github.com/getgauge/html-report/generator.toStep(0x420765180, 0x0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:262 +0x346
github.com/getgauge/html-report/generator.getItems(0x420768ac0, 0x2, 0x2, 0x324cc0, 0x1, 0x536870)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:329 +0x376
github.com/getgauge/html-report/generator.toConcept(0x420709140, 0x0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:273 +0x88
github.com/getgauge/html-report/generator.getItems(0x4206ba3d8, 0x1, 0x1, 0x420747700, 0x1, 0x1)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:333 +0xee
github.com/getgauge/html-report/generator.toScenario(0x4206d35e0, 0xffffffffffffffff, 0x0)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:236 +0x173
github.com/getgauge/html-report/generator.toSpec(0x420653500, 0x420ae2960)
	/tmp/src/github.com/getgauge/html-report/generator/transform.go:184 +0x57c
github.com/getgauge/html-report/generator.generateSpecDiv(0x4f7620, 0x4206baa38, 0x420653500)
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:378 +0x47
github.com/getgauge/html-report/generator.generateSpecPage(0x4206603f0, 0x420653500, 0x4f7620, 0x4206baa38, 0x420a0cf00)
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:356 +0x29a
created by github.com/getgauge/html-report/generator.GenerateReports
	/tmp/src/github.com/getgauge/html-report/generator/generate.go:243 +0x403
Specifications:	16 executed	13 passed	3 failed	13 skipped
Scenarios:	17 executed	14 passed	3 failed	15 skipped
```
**Version**
```
Gauge version: 0.7.1.nightly-2017-01-06

Plugins
-------
html-report (3.0.1.nightly-2017-01-10)
java (0.5.2.nightly-2016-12-20)
ruby (0.3.1)
```

**Comment by BugDiver** [comment]
### Dev Notes:-
 
To fix this issue the changes need to be done in Gauge core.
When an inline data table is passed to a concept the gauge set the parameter as SpecialTable_Parameter (CSV) in steps. However, the parameter does not have a `name`.
The Html Report plugin access the `name` field of the parameter to create links for Special parameters.

Example :- 

example.cpt
```
# a concept with <table>
* step consuming the <table>
```

example.spec
```
Specification
=========
scenario
--------
* a concept with 
   |header|
   --------
   |foo   |
   |bar   |

```

In result, gauge sets the parameter `table` as a SpecialTable_Param in step.

**Comment by sguptatw** [comment]
Not getting the exception anymore. However in the HTML report the step parameter is not displayed.
