### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by iskoc9002** [getgauge/html-report#238]
Hi,
When I used to  maven command with multiple flags parameters **-Dflags**="**--only=!serial** ,--max-retries-count=2" end of the test html-report threw error. You can find error details below.

runtime error: invalid memory address or nil pointer dereference
09:31:08 [signal 0xc0000005 code=0x0 addr=0x20 pc=0x72a714]
09:31:08 goroutine 1 [running]:
09:31:08 github.com/getgauge/html-report/generator.computeTableDrivenStatuses(
09:31:08 0xc042372dc0)
09:31:08 	/tmp/src/github.com/getgauge/html-report/generator/transform.go:396 +0x34
09:31:08 github.com/getgauge/html-report/generator.toSpec(0xc04237e1b0, 0xc04231e5c0)
09:31:08 	/tmp/src/github.com/getgauge/html-report/generator/transform.go:348 +0x1466
09:31:08 github.com/getgauge/html-report/generator.ToSuiteResult(0xc042415fc0, 0x36, 0xc042372840, 0x5e)
09:31:08 	/tmp/src/github.com/getgauge/html-report/generator/transform.go:68 +0x7ea
09:31:08 main.createReport(0xc042433440, 0x85b701, 0xc0420122a0, 0x0, 0x0, 0x0, 0x0)
09:31:08 	/godata/pipelines/HTML_Report/htmlReport.go:139 +0xe5
09:31:08 main.(*reportAccumulator).Meta(0xc04207dd10, 0xc042433440)
09:31:08 	/godata/pipelines/HTML_Report/htmlReport.go
09:31:08 :75 +0x25b
09:31:08 main.(*reportAccumulator).Meta-fm(
09:31:08 0xc042433440)
09:31:08 	/godata/pipelines/HTML_Report/htmlReport.go
09:31:08 :127 +0x3b
09:31:08 github.com/getgauge/html-report/listener.(*GaugeListener).processMessages(
09:31:08 0xc04207dce0, 0xc04216da40)
09:31:08 	/tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:98 +0x31d
09:31:08 github.com/getgauge/html-report/listener.(*GaugeListener).Start(0xc04207dce0)
09:31:08 	/tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:75
09:31:08 +0xbe
09:31:08 main.createExecutionReport()
09:31:08 	/godata/pipelines/HTML_Report/htmlReport.go:129 +0x1ae
09:31:08 main.main()
09:31:08 	/godata/pipelines/HTML_Report/main.go:59 +0x2b2

**Comment by negiDharmendra** [comment]
@iskoc9002 Need few details to debug this issue.

- Please run `gauge -v` on your terminal and share the details with us.
- Which OS you are on.
- Java version

**Comment by iskoc9002** [comment]
Hi,
I tried to 2 different OS.
**First one:**
**>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"**
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763

**Second one:**
**>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"**
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

**>java -version**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**>gauge -v**
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3.nightly-2019-04-10)
screenshot (0.0.1)

**Comment by negiDharmendra** [comment]
@iskoc9002  I am not able to replicate this iisue. My setup is as following. Can you create a sample gauge maven project `gauge init java_maven` and see if you face the issue. If not is it possibel for you to share a sample project to replicate this issue.

 **systeminfo | findstr /B /C:"OS Name" /C:"OS Version"**
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
```

gauge -v
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.3)
js (2.3.6.nightly-2019-09-24)
python (0.3.5)
screenshot (0.0.1)
xml-report (0.2.1)

```

**Comment by nehashri** [comment]
@iskoc9002 Any updates? Can you share a sample project to help reproduce the issue?

**Comment by nehashri** [comment]
Closing due to inactivity. Please feel free to reopen the issue with more details.
