### ISSUE TITLE
Gauge crashes after encountering an exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/html-report#281]
### Expected behavior
Should be able to build the report seamlessly

### Actual behavior
Getting the exception
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x81368d]
goroutine 487 [running]:
github.com/getgauge/html-report/generator.computeTableDrivenStatuses(0xc0002ef340)
	/home/runner/work/html-report/html-report/generator/transform.go:416 +0x2d
github.com/getgauge/html-report/generator.toSpec(0xc000309400, 0xc000028204, 0x32, 0x2)
	/home/runner/work/html-report/html-report/generator/transform.go:368 +0x1397
github.com/getgauge/html-report/generator.ToSuiteResult(0xc000028204, 0x32, 0xc000434c00, 0x46)
	/home/runner/work/html-report/html-report/generator/transform.go:69 +0x8be
main.createReport(0xc0001100c0, 0x9d6101)
	/home/runner/work/html-report/html-report/htmlReport.go:54 +0xd5
main.(*handler).NotifySuiteResult(0xc00000e310, 0x9d2e40, 0xc000110090, 0xc0001100c0, 0xc00000e310, 0xc000110090, 0xc000087a50)
	/home/runner/work/html-report/html-report/handler.go:47 +0x30
github.com/getgauge/html-report/gauge_messages._Reporter_NotifySuiteResult_Handler(0x8cd140, 0xc00000e310, 0x9d2e40, 0xc000110090, 0xc000341920, 0x0, 0x9d2e40, 0xc000110090, 0xc000386000, 0xad0a)
	/home/runner/work/html-report/html-report/gauge_messages/services.pb.go:1316 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00, 0xc0001113b0
, 0xc43c00, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001fa450, 0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa5
```

### Steps to reproduce
This is an intermittent issue. However this happens when Taiko was waiting for a dialog box to appear but if the dialog box is not available
```
{ Error: No dialog is showing
at _enqueueCommand (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:94:35)
at Chrome._handleMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
at WebSocket._ws.on (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
at WebSocket.emit (events.js:198:13)
at Receiver.receiverOnMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/websocket.js:970:20)
at Receiver.emit (events.js:198:13)
at Receiver.dataMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/receiver.js:517:14)
at perMessageDeflate.decompress (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/receiver.js:468:23)
at _decompress (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/permessage-deflate.js:308:9)
at _inflate.flush (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/permessage-deflate.js:391:7)
request:
{ method: 'Page.handleJavaScriptDialog',
params: { accept: true, promptText: '' },
sessionId: undefined },
response: { code: -32602, message: 'No dialog is showing' } }
```
So Gauge crashes and does not proceed after encountering this no dialog error
```
{ Error: No dialog is showing
at _enqueueCommand (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:94:35)
at Chrome._handleMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
at WebSocket._ws.on (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
at WebSocket.emit (events.js:198:13)
at Receiver.receiverOnMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/websocket.js:970:20)
at Receiver.emit (events.js:198:13)
at Receiver.dataMessage (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/receiver.js:517:14)
at perMessageDeflate.decompress (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/receiver.js:468:23)
at _decompress (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/permessage-deflate.js:308:9)
at _inflate.flush (/var/lib/go-agent/pipelines/Bahmni-ndhm-compliance/node_modules/ws/lib/permessage-deflate.js:391:7)
request:
{ method: 'Page.handleJavaScriptDialog',
params: { accept: true, promptText: '' },
sessionId: undefined },
response: { code: -32602, message: 'No dialog is showing' } }
          * Close visit
            
            Failed Step: Close visit
            Specification: specs/HIPDataTransfer/OPDVisit.spec
            Error Message: error reading from server: EOF
            Stacktrace: 

            Error Message: Runner is not Alive
            Stacktrace: 

    Error Message: Runner is not Alive
    Stacktrace: 

  Error Message: Runner is not Alive
  Stacktrace: 

  Error Message: Runner is not Alive
  Stacktrace: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x81368d]
goroutine 487 [running]:
github.com/getgauge/html-report/generator.computeTableDrivenStatuses(0xc0002ef340)
	/home/runner/work/html-report/html-report/generator/transform.go:416 +0x2d
github.com/getgauge/html-report/generator.toSpec(0xc000309400, 0xc000028204, 0x32, 0x2)
	/home/runner/work/html-report/html-report/generator/transform.go:368 +0x1397
github.com/getgauge/html-report/generator.ToSuiteResult(0xc000028204, 0x32, 0xc000434c00, 0x46)
	/home/runner/work/html-report/html-report/generator/transform.go:69 +0x8be
main.createReport(0xc0001100c0, 0x9d6101)
	/home/runner/work/html-report/html-report/htmlReport.go:54 +0xd5
main.(*handler).NotifySuiteResult(0xc00000e310, 0x9d2e40, 0xc000110090, 0xc0001100c0, 0xc00000e310, 0xc000110090, 0xc000087a50)
	/home/runner/work/html-report/html-report/handler.go:47 +0x30
github.com/getgauge/html-report/gauge_messages._Reporter_NotifySuiteResult_Handler(0x8cd140, 0xc00000e310, 0x9d2e40, 0xc000110090, 0xc000341920, 0x0, 0x9d2e40, 0xc000110090, 0xc000386000, 0xad0a)
	/home/runner/work/html-report/html-report/gauge_messages/services.pb.go:1316 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00, 0xc0001113b0
, 0xc43c00, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001fa450, 0xc000001500, 0x9d6038, 0xc000001800, 0xc000338d00)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa5
Error occurred while waiting for plugin process to finish.
```

### Gauge version
```
Gauge version: 1.1.8
Commit Hash: b1501f4

Plugins
-------
html-report (4.0.12)
java (0.7.15)
js (2.3.16)
screenshot (0.0.1)
```

**Comment by mboiman** [comment]
This challenge is still a disorganized problem

**Comment by chadlwilson** [comment]
Should be fixed (or worked around) by #362
