### ISSUE TITLE
Failed to generate HTML report

### ISSUE THREAD

**Issue by rajiesh** [getgauge/html-report#70]
HTML report failed to generate and throws up below exception,

```
04:46:59.689 fatal error: checkdead: runnable g
04:46:59.689 
04:46:59.690 runtime stack:
04:46:59.690 runtime.throw(0x8b92fc)
04:46:59.695    /usr/local/go/src/runtime/panic.go:491 +0xad
04:46:59.696 checkdead()
04:46:59.696    /usr/local/go/src/runtime/proc.c:2828 +0x287
04:46:59.696 mput(0x8c4da0)
04:46:59.696    /usr/local/go/src/runtime/proc.c:3175 +0x47
04:46:59.696 stopm()
04:46:59.696    /usr/local/go/src/runtime/proc.c:1176 +0xea
04:46:59.696 findrunnable(0xc208012000)
04:46:59.696    /usr/local/go/src/runtime/proc.c:1487 +0x562
04:46:59.696 schedule()
04:46:59.697    /usr/local/go/src/runtime/proc.c:1575 +0x151
04:46:59.697 runtime.park_m(0xc208000120)
04:46:59.697    /usr/local/go/src/runtime/proc.c:1654 +0x113
04:46:59.697 runtime.mcall(0x432dd4)
04:46:59.697    /usr/local/go/src/runtime/asm_amd64.s:186 +0x5a
04:46:59.697 
04:46:59.697 goroutine 1 [runnable]:
04:46:59.697 net.(*pollDesc).Wait(0xc208010450, 0x72, 0x0, 0x0)
04:46:59.697    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
04:46:59.698 net.(*pollDesc).WaitRead(0xc208010450, 0x0, 0x0)
04:46:59.698    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
04:46:59.698 net.(*netFD).Read(0xc2080103f0, 0xc20805e000, 0x2000, 0x2000, 0x0, 0x7f21c7ab2a70, 0xc20800be00)
04:46:59.698    /usr/local/go/src/net/fd_unix.go:242 +0x40f
04:46:59.698 net.(*conn).Read(0xc20803e018, 0xc20805e000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
04:46:59.698    /usr/local/go/src/net/net.go:121 +0xdc
04:46:59.698 github.com/getgauge/html-report/listener.(*GaugeListener).Start(0xc20801e7e0)
04:46:59.698    /tmp/src/github.com/getgauge/html-report/listener/gaugeListener.go:54 +0xc7
04:46:59.698 main.createExecutionReport()
04:46:59.698    /Users/stechops/Library/Application Support/Go Agent/pipelines/HTML_Report/htmlReport.go:87 +0x1d4
04:46:59.699 main.main()
04:46:59.699    /Users/stechops/Library/Application Support/Go Agent/pipelines/HTML_Report/main.go:28 +0xd2
04:47:00.648 Unable to connect to plugin Html Report 2.0.0. [Warning] Failed to send message to plugin: html-report  write tcp 127.0.0.1:38432: connection reset by peer
04:47:00.648 
04:47:00.648 Failed to kill plugin Html Report 2.0.0. os: process already finished
```

This is an intermittent issue and more specifically on an agent, pls check this [Go pipeline](https://build.go.cd/go/tab/build/detail/regression-gauge/227/regression-linux/2/OOM-tests), can work with you to debug it further

**Comment by mahendrakariya** [comment]
@rajiesh Are you still facing this issue?

**Comment by mahendrakariya** [comment]
@rajiesh Are updates on this?

**Comment by rajiesh** [comment]
Not seeing this issue now, so closing it
